import type { IconType } from "react-icons";
import {
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiNginx,
  SiMysql,
  SiPostgresql,
  SiSpringboot,
  SiTailwindcss,
  SiJavascript,
  SiGit,
  SiGithub,
  SiLinux,
  SiIntellijidea,
  SiPostman,
  SiSonarqubecloud,
  SiAsana,
  SiDbeaver,
} from "react-icons/si";
import { VscCode } from "react-icons/vsc";
import { FaAws, FaJava } from "react-icons/fa";
import {
  HiOutlineArrowRight,
  HiOutlineArrowTopRightOnSquare,
  HiOutlineBars3,
  HiOutlineBriefcase,
  HiOutlineChevronRight,
  HiOutlineCloud,
  HiOutlineCodeBracket,
  HiOutlineComputerDesktop,
  HiOutlineEnvelope,
  HiOutlineLink,
  HiOutlineMapPin,
  HiOutlinePaperAirplane,
  HiOutlineServerStack,
  HiOutlineSparkles,
  HiOutlineWrenchScrewdriver,
  HiOutlineXMark,
  HiOutlineCircleStack,
} from "react-icons/hi2";
import { FaLinkedin } from "react-icons/fa6";

export type AppIcon = IconType;

export const heroTechIcons: { Icon: AppIcon; color: string; label: string }[] = [
  { Icon: SiReact, color: "#61DAFB", label: "React.js" },
  { Icon: FaAws, color: "#FF9900", label: "AWS" },
  { Icon: SiNodedotjs, color: "#339933", label: "Node.js" },
  { Icon: SiNginx, color: "#009639", label: "Nginx" },
  { Icon: SiNextdotjs, color: "#111111", label: "Next.js" },
  { Icon: FaJava, color: "#007396", label: "Java" },
];

export const skillCategoryIcons: AppIcon[] = [
  HiOutlineCodeBracket,
  HiOutlineServerStack,
  HiOutlineCircleStack,
  HiOutlineCloud,
  HiOutlineWrenchScrewdriver,
  HiOutlineComputerDesktop,
];

export const skillBrandIcons: Record<string, AppIcon> = {
  "React.js": SiReact,
  "Next.js": SiNextdotjs,
  JavaScript: SiJavascript,
  "Tailwind CSS": SiTailwindcss,
  CSS: HiOutlineCodeBracket,
  HTML: HiOutlineCodeBracket,
  JSP: HiOutlineCodeBracket,
  AJAX: HiOutlineCodeBracket,
  "Node.js": SiNodedotjs,
  Java: FaJava,
  "Core Java": FaJava,
  J2EE: FaJava,
  "Spring Boot": SiSpringboot,
  Hibernate: FaJava,
  Struts: FaJava,
  JSON: HiOutlineCodeBracket,
  MySQL: SiMysql,
  PostgreSQL: SiPostgresql,
  "Oracle Database": HiOutlineCircleStack,
  JDBC: HiOutlineCircleStack,
  DevOps: HiOutlineCloud,
  "Amazon EC2": FaAws,
  "Amazon S3": FaAws,
  "Amazon CloudFront": FaAws,
  "Amazon Route 53": FaAws,
  "Elastic Load Balancing": FaAws,
  Nginx: SiNginx,
  PM2: HiOutlineServerStack,
  Ubuntu: SiLinux,
  GoDaddy: HiOutlineCloud,
  "Web Hosting": HiOutlineCloud,
  cPanel: HiOutlineCloud,
  Git: SiGit,
  GitHub: SiGithub,
  Postman: SiPostman,
  "IntelliJ IDEA": SiIntellijidea,
  "VS Code": VscCode,
  Cursor: HiOutlineSparkles,
  DBeaver: SiDbeaver,
  Adminer: HiOutlineCircleStack,
  STS: SiSpringboot,
  SonarQube: SiSonarqubecloud,
  OpenProject: HiOutlineBriefcase,
  MobaXterm: HiOutlineComputerDesktop,
  Electerm: HiOutlineComputerDesktop,
  Asana: SiAsana,
  MyEclipse: FaJava,
  SOS: HiOutlineWrenchScrewdriver,
  Workforce: HiOutlineBriefcase,
  Workcloud: HiOutlineCloud,
};

export {
  HiOutlineArrowRight,
  HiOutlineArrowTopRightOnSquare,
  HiOutlineBars3,
  HiOutlineBriefcase,
  HiOutlineChevronRight,
  HiOutlineEnvelope,
  HiOutlineLink,
  HiOutlineMapPin,
  HiOutlinePaperAirplane,
  HiOutlineSparkles,
  HiOutlineXMark,
  FaLinkedin,
};
